### ISSUE TITLE
Пометка каждого документа точкой доступа

### ISSUE THREAD

**Issue by Shekhovtsovy** [lowbase/yii2-lowbase#6]
Добавить основное поле "точка доступа" в сущность документ в виде списка со всеми точками доступа (можно помечать системные документы, не доступные для удаления, редактирования, кроме как админом, закреплять возможности по конкретным документам для разных пользователей).

Добавить по-умолчанию роль Программист (он же root) -работающий над Frontend
Добавить по-умолчанию точку доступа (системный документ)

**Comment by maximal** [comment]
Так, а зачем нам это нужно?

**Comment by Shekhovtsovy** [comment]
Сама система работает по принципу: "программирование от контента". т.е. сайт начинаем заполнять по структуре и содержанию еще не приступив к программированию (либо делая это параллельно). Разумеется программный код во Frontend-модуле будет опираться на конкретные документы. 
Создаем точку доступа "системный документ". помечаем такой точкой доки, на которые опирается код. и даем доступ на эти права роли "Программист", чтобы модераторы не поломали сайт. Это как один из вариантов (самый главный)

**Comment by maximal** [comment]
Блин, пиши в сообщениях коммитов номер ишьюса к которому они относятся.

„Поработал над #6“ или что-то в этом духе.

**Comment by lowbase** [comment]
Закрыл все issue сразу, т.к. cms перенес на модульную структуру. И все они потеряли актуальность
